services:
  mail-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    volumes:
      - .:/app
    container_name: mail_api
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mail-network
  
  mail-api-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    volumes:
      - .:/app
    container_name: mail_api_migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mail-network
  
  postgres:
    image: postgres:16-alpine
    container_name: mail_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "mail_db"
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - mail-network
  
  adminer:
    image: adminer:4.7
    container_name: mail_adminer
    ports:
      - "8001:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      ADMINER_DESIGN: pepa-linha
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge